/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Action required when performing CMD_PREFLIGHT_STORAGE
 */
public class MAV_PREFLIGHT_STORAGE_ACTION {
   public static final int MAV_PFS_CMD_READ_ALL = 0; /* Read all parameters from storage | */
   public static final int MAV_PFS_CMD_WRITE_ALL = 1; /* Write all parameters to storage | */
   public static final int MAV_PFS_CMD_CLEAR_ALL = 2; /* Clear all  parameters in storage | */
   public static final int MAV_PFS_CMD_READ_SPECIFIC = 3; /* Read specific parameters from storage | */
   public static final int MAV_PFS_CMD_WRITE_SPECIFIC = 4; /* Write specific parameters to storage | */
   public static final int MAV_PFS_CMD_CLEAR_SPECIFIC = 5; /* Clear specific parameters in storage | */
   public static final int MAV_PFS_CMD_DO_NOTHING = 6; /* do nothing | */
   public static final int MAV_PREFLIGHT_STORAGE_ACTION_ENUM_END = 7; /*  | */
}
            