/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Possible transport layers to set and get parameters via mavlink during a parameter transaction.
 */
public class PARAM_TRANSACTION_TRANSPORT {
   public static final int PARAM_TRANSACTION_TRANSPORT_PARAM = 0; /* Transaction over param transport. | */
   public static final int PARAM_TRANSACTION_TRANSPORT_PARAM_EXT = 1; /* Transaction over param_ext transport. | */
   public static final int PARAM_TRANSACTION_TRANSPORT_ENUM_END = 2; /*  | */
}
            