/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * Possible parameter transaction actions.
 */
public class PARAM_TRANSACTION_ACTION {
   public static final int PARAM_TRANSACTION_ACTION_START = 0; /* Commit the current parameter transaction. | */
   public static final int PARAM_TRANSACTION_ACTION_COMMIT = 1; /* Commit the current parameter transaction. | */
   public static final int PARAM_TRANSACTION_ACTION_CANCEL = 2; /* Cancel the current parameter transaction. | */
   public static final int PARAM_TRANSACTION_ACTION_ENUM_END = 3; /*  | */
}
            