/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * RADIO_LINK_STATS flags (bitmask).
 */
public class RADIO_LINK_STATS_FLAGS {
   public static final int RADIO_LINK_STATS_FLAGS_RSSI_DBM = 1; /* Rssi are in negative dBm. Values 0..254 corresponds to 0..-254 dBm. | */
   public static final int RADIO_LINK_STATS_FLAGS_ENUM_END = 2; /*  | */
}
            