/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * RADIO_RC_CHANNELS flags (bitmask).
 */
public class RADIO_RC_CHANNELS_FLAGS {
   public static final int RADIO_RC_CHANNELS_FLAGS_FAILSAFE = 1; /* Failsafe is active. | */
   public static final int RADIO_RC_CHANNELS_FLAGS_FRAME_MISSED = 2; /* Indicates that the current frame has not been received. Channel values are frozen. | */
   public static final int RADIO_RC_CHANNELS_FLAGS_ENUM_END = 3; /*  | */
}
            