/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * The frame of a target observation from an onboard sensor.
 */
public class TARGET_OBS_FRAME {
   public static final int TARGET_OBS_FRAME_LOCAL_NED = 0; /* NED local tangent frame (x: North, y: East, z: Down) with origin fixed relative to earth. | */
   public static final int TARGET_OBS_FRAME_BODY_FRD = 1; /* FRD local frame aligned to the vehicle's attitude (x: Forward, y: Right, z: Down) with an origin that travels with vehicle. | */
   public static final int TARGET_OBS_FRAME_LOCAL_OFFSET_NED = 2; /* NED local tangent frame (x: North, y: East, z: Down) with an origin that travels with vehicle. | */
   public static final int TARGET_OBS_FRAME_OTHER = 3; /* Other sensor frame for target observations neither in local NED nor in body FRD. | */
   public static final int TARGET_OBS_FRAME_ENUM_END = 4; /*  | */
}
            