/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * These flags indicate the sensor reporting capabilities for TARGET_ABSOLUTE.
 */
public class TARGET_ABSOLUTE_SENSOR_CAPABILITY_FLAGS {
   public static final int TARGET_ABSOLUTE_SENSOR_CAPABILITY_POSITION = 1; /*  | */
   public static final int TARGET_ABSOLUTE_SENSOR_CAPABILITY_VELOCITY = 2; /*  | */
   public static final int TARGET_ABSOLUTE_SENSOR_CAPABILITY_ACCELERATION = 4; /*  | */
   public static final int TARGET_ABSOLUTE_SENSOR_CAPABILITY_ATTITUDE = 8; /*  | */
   public static final int TARGET_ABSOLUTE_SENSOR_CAPABILITY_RATES = 16; /*  | */
   public static final int TARGET_ABSOLUTE_SENSOR_CAPABILITY_FLAGS_ENUM_END = 17; /*  | */
}
            