/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

package com.MAVLink.enums;

/**
 * WiFi wireless security protocols.
 */
public class WIFI_NETWORK_SECURITY {
   public static final int WIFI_NETWORK_SECURITY_UNDEFINED = 0; /* Undefined or unknown security protocol. | */
   public static final int WIFI_NETWORK_SECURITY_OPEN = 1; /* Open network, no security. | */
   public static final int WIFI_NETWORK_SECURITY_WEP = 2; /* WEP. | */
   public static final int WIFI_NETWORK_SECURITY_WPA1 = 3; /* WPA1. | */
   public static final int WIFI_NETWORK_SECURITY_WPA2 = 4; /* WPA2. | */
   public static final int WIFI_NETWORK_SECURITY_WPA3 = 5; /* WPA3. | */
   public static final int WIFI_NETWORK_SECURITY_ENUM_END = 6; /*  | */
}
            