/***************************** BEGIN LICENSE BLOCK ***************************

 The contents of this file are subject to the Mozilla Public License, v. 2.0.
 If a copy of the MPL was not distributed with this file, You can obtain one
 at http://mozilla.org/MPL/2.0/.

 Software distributed under the License is distributed on an "AS IS" basis,
 WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
 for the specific language governing rights and limitations under the License.

 Copyright (C) 2026 GeoRobotix Innovative Research. All Rights Reserved.

 ******************************* END LICENSE BLOCK ***************************/
package org.sensorhub.impl.sensor.nmeaais.helpers;

import org.vast.swe.SWEBuilders.*;
import org.vast.swe.SWEConstants;
import org.vast.swe.SWEHelper;

/**
 * The NmeaAisFieldHelper is used to help standardize building NMEA AIS fields that are used in multiple AIS Reports
 */
public class NmeaAisHelper extends SWEHelper{

    public CategoryBuilder createNmeaMessageId() {
        return createCategory()
                .label("Message Id")
                .description("AIS Message Identifier")
                .definition(getPropertyUri("MessageId"));

    }

    public TextBuilder createReportDescription() {
        return createText()
                .label("Report Description")
                .description("Describes the report based on the Message Id provided")
                .definition(getPropertyUri("ReportDescription"));
    }

    public CountBuilder createRepeatIndicator(){
        return createCount()
                .label("Repeat Indicator")
                .description("Used by the repeater to indicate how many times a message has been repeated; 0-3; 0 = default")
                .definition(SWEHelper.getPropertyUri("repeat"));
    }

    public TextBuilder createMssi() {
        return createText()
                .label("MMSI Number")
                .description("MMSI Number")
                .definition(SWEHelper.getPropertyUri("Mmsi"));
    }

    public TextBuilder createPositionAccuracy() {
        return createText()
                .label("Position Accuracy")
                .description("1 = high (<= 10 m); 0 = low (> 10 m); 0 = default")
                .definition(SWEHelper.getPropertyUri("PositionAccuracy"));
    }

    public CategoryBuilder createEpfd() {
        return createCategory()
                .label("EPFD Type")
                .description("Type of Electronic Position Fixing Device: 0 = undefined, 1 = GPS, 2 = GLONASS, 3 = Combined GPS/GLONASS, 4 = Loran-C, 5 = Chayka, 6 = Integrated navigation system, 7 = Surveyed, 8 = Galileo, 15 = internal GNSS")
                .definition(SWEHelper.getPropertyUri("EpfdType"));
    }

    public BooleanBuilder createRAIM(){
        return createBoolean()
                .label("Receiver Autonomous Integrity Monitoring")
                .description("false = RAIM not in use; true = RAIM in use")
                .definition(SWEHelper.getPropertyUri("Raim"));
    }

    public CountBuilder createUtcSecond() {
        return createCount()
                .label("UTC Second")
                .description("UTC second when report was generated by the EPFS (0-59); " +
                             "60 = not available (default); " +
                             "61 = manual input mode; " +
                             "62 = dead reckoning mode; " +
                             "63 = positioning system inoperative")
                .definition(SWEHelper.getPropertyUri("UtcSecond"))
                .addNilValue(AisCodeHelper.UtcSecondStatus.NOT_AVAILABLE.getCode(),  SWEConstants.NIL_UNKNOWN)
                .addNilValue(AisCodeHelper.UtcSecondStatus.MANUAL_INPUT.getCode(),   SWEConstants.NIL_INAPPLICABLE)
                .addNilValue(AisCodeHelper.UtcSecondStatus.DEAD_RECKONING.getCode(), SWEConstants.NIL_INAPPLICABLE)
                .addNilValue(AisCodeHelper.UtcSecondStatus.INOPERATIVE.getCode(),    SWEConstants.NIL_MISSING);
    }

    public CategoryBuilder createOffPositionIndicator() {
        return createCategory()
                .label("Off Position Indicator")
                .description("For floating aids-to-navigation: 0 = on position; 1 = off position. Only valid if UTC second is 0-59.")
                .definition(SWEHelper.getPropertyUri("OffPositionIndicator"))
                .addAllowedValues(
                    AisCodeHelper.OffPositionIndicator.ON_POSITION.getDescription(),
                    AisCodeHelper.OffPositionIndicator.OFF_POSITION.getDescription()
                )
                .addNilValue("N/A", SWEConstants.NIL_INAPPLICABLE);
    }

    public TextBuilder createAssignedMode(){
        return createText()
                .label("Assigned Mode Flag")
                .description("0 = station operating in autonomous and continuous mode = default; 1 = station operating in assigned mode")
                .definition(SWEHelper.getPropertyUri("AssignedMode"));
    }

    public BooleanBuilder createDte(){
        return createBoolean()
                .label("Data Terminal Equipment")
                .description("Data terminal equipment (DTE) available; 0 = true = available; 1 = false = not available = default")
                .definition(SWEHelper.getPropertyUri("Dte"));
    }

    public TextBuilder createVesselName() {
        return createText()
                .label("Vessel Name")
                .description("Maximum 20 characters per ITU-R M.1371-5; '@' padding stripped")
                .definition(SWEHelper.getPropertyUri("VesselName"));
    }
}
