/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SERIAL_UDB_EXTRA_F17 PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F17 format
 */
public class msg_serial_udb_extra_f17 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F17 = 183;
    public static final int MAVLINK_MSG_LENGTH = 12;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F17;

    
    /**
     * SUE Feed Forward Gain
     */
    @Description("SUE Feed Forward Gain")
    @Units("")
    public float sue_feed_forward;
    
    /**
     * SUE Max Turn Rate when Navigating
     */
    @Description("SUE Max Turn Rate when Navigating")
    @Units("")
    public float sue_turn_rate_nav;
    
    /**
     * SUE Max Turn Rate in Fly By Wire Mode
     */
    @Description("SUE Max Turn Rate in Fly By Wire Mode")
    @Units("")
    public float sue_turn_rate_fbw;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F17;

        packet.payload.putFloat(sue_feed_forward);
        packet.payload.putFloat(sue_turn_rate_nav);
        packet.payload.putFloat(sue_turn_rate_fbw);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a serial_udb_extra_f17 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.sue_feed_forward = payload.getFloat();
        this.sue_turn_rate_nav = payload.getFloat();
        this.sue_turn_rate_fbw = payload.getFloat();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_serial_udb_extra_f17() {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F17;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_serial_udb_extra_f17( float sue_feed_forward, float sue_turn_rate_nav, float sue_turn_rate_fbw) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F17;

        this.sue_feed_forward = sue_feed_forward;
        this.sue_turn_rate_nav = sue_turn_rate_nav;
        this.sue_turn_rate_fbw = sue_turn_rate_fbw;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_serial_udb_extra_f17( float sue_feed_forward, float sue_turn_rate_nav, float sue_turn_rate_fbw, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F17;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sue_feed_forward = sue_feed_forward;
        this.sue_turn_rate_nav = sue_turn_rate_nav;
        this.sue_turn_rate_fbw = sue_turn_rate_fbw;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_serial_udb_extra_f17(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F17;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

          
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F17 - sysid:"+sysid+" compid:"+compid+" sue_feed_forward:"+sue_feed_forward+" sue_turn_rate_nav:"+sue_turn_rate_nav+" sue_turn_rate_fbw:"+sue_turn_rate_fbw+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F17";
    }
}
        