/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SERIAL_UDB_EXTRA_F20 PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F20 format
 */
public class msg_serial_udb_extra_f20 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F20 = 186;
    public static final int MAVLINK_MSG_LENGTH = 25;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F20;

    
    /**
     * SUE UDB PWM Trim Value on Input 1
     */
    @Description("SUE UDB PWM Trim Value on Input 1")
    @Units("")
    public short sue_trim_value_input_1;
    
    /**
     * SUE UDB PWM Trim Value on Input 2
     */
    @Description("SUE UDB PWM Trim Value on Input 2")
    @Units("")
    public short sue_trim_value_input_2;
    
    /**
     * SUE UDB PWM Trim Value on Input 3
     */
    @Description("SUE UDB PWM Trim Value on Input 3")
    @Units("")
    public short sue_trim_value_input_3;
    
    /**
     * SUE UDB PWM Trim Value on Input 4
     */
    @Description("SUE UDB PWM Trim Value on Input 4")
    @Units("")
    public short sue_trim_value_input_4;
    
    /**
     * SUE UDB PWM Trim Value on Input 5
     */
    @Description("SUE UDB PWM Trim Value on Input 5")
    @Units("")
    public short sue_trim_value_input_5;
    
    /**
     * SUE UDB PWM Trim Value on Input 6
     */
    @Description("SUE UDB PWM Trim Value on Input 6")
    @Units("")
    public short sue_trim_value_input_6;
    
    /**
     * SUE UDB PWM Trim Value on Input 7
     */
    @Description("SUE UDB PWM Trim Value on Input 7")
    @Units("")
    public short sue_trim_value_input_7;
    
    /**
     * SUE UDB PWM Trim Value on Input 8
     */
    @Description("SUE UDB PWM Trim Value on Input 8")
    @Units("")
    public short sue_trim_value_input_8;
    
    /**
     * SUE UDB PWM Trim Value on Input 9
     */
    @Description("SUE UDB PWM Trim Value on Input 9")
    @Units("")
    public short sue_trim_value_input_9;
    
    /**
     * SUE UDB PWM Trim Value on Input 10
     */
    @Description("SUE UDB PWM Trim Value on Input 10")
    @Units("")
    public short sue_trim_value_input_10;
    
    /**
     * SUE UDB PWM Trim Value on Input 11
     */
    @Description("SUE UDB PWM Trim Value on Input 11")
    @Units("")
    public short sue_trim_value_input_11;
    
    /**
     * SUE UDB PWM Trim Value on Input 12
     */
    @Description("SUE UDB PWM Trim Value on Input 12")
    @Units("")
    public short sue_trim_value_input_12;
    
    /**
     * SUE Number of Input Channels
     */
    @Description("SUE Number of Input Channels")
    @Units("")
    public short sue_number_of_inputs;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F20;

        packet.payload.putShort(sue_trim_value_input_1);
        packet.payload.putShort(sue_trim_value_input_2);
        packet.payload.putShort(sue_trim_value_input_3);
        packet.payload.putShort(sue_trim_value_input_4);
        packet.payload.putShort(sue_trim_value_input_5);
        packet.payload.putShort(sue_trim_value_input_6);
        packet.payload.putShort(sue_trim_value_input_7);
        packet.payload.putShort(sue_trim_value_input_8);
        packet.payload.putShort(sue_trim_value_input_9);
        packet.payload.putShort(sue_trim_value_input_10);
        packet.payload.putShort(sue_trim_value_input_11);
        packet.payload.putShort(sue_trim_value_input_12);
        packet.payload.putUnsignedByte(sue_number_of_inputs);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a serial_udb_extra_f20 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.sue_trim_value_input_1 = payload.getShort();
        this.sue_trim_value_input_2 = payload.getShort();
        this.sue_trim_value_input_3 = payload.getShort();
        this.sue_trim_value_input_4 = payload.getShort();
        this.sue_trim_value_input_5 = payload.getShort();
        this.sue_trim_value_input_6 = payload.getShort();
        this.sue_trim_value_input_7 = payload.getShort();
        this.sue_trim_value_input_8 = payload.getShort();
        this.sue_trim_value_input_9 = payload.getShort();
        this.sue_trim_value_input_10 = payload.getShort();
        this.sue_trim_value_input_11 = payload.getShort();
        this.sue_trim_value_input_12 = payload.getShort();
        this.sue_number_of_inputs = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_serial_udb_extra_f20() {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F20;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_serial_udb_extra_f20( short sue_trim_value_input_1, short sue_trim_value_input_2, short sue_trim_value_input_3, short sue_trim_value_input_4, short sue_trim_value_input_5, short sue_trim_value_input_6, short sue_trim_value_input_7, short sue_trim_value_input_8, short sue_trim_value_input_9, short sue_trim_value_input_10, short sue_trim_value_input_11, short sue_trim_value_input_12, short sue_number_of_inputs) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F20;

        this.sue_trim_value_input_1 = sue_trim_value_input_1;
        this.sue_trim_value_input_2 = sue_trim_value_input_2;
        this.sue_trim_value_input_3 = sue_trim_value_input_3;
        this.sue_trim_value_input_4 = sue_trim_value_input_4;
        this.sue_trim_value_input_5 = sue_trim_value_input_5;
        this.sue_trim_value_input_6 = sue_trim_value_input_6;
        this.sue_trim_value_input_7 = sue_trim_value_input_7;
        this.sue_trim_value_input_8 = sue_trim_value_input_8;
        this.sue_trim_value_input_9 = sue_trim_value_input_9;
        this.sue_trim_value_input_10 = sue_trim_value_input_10;
        this.sue_trim_value_input_11 = sue_trim_value_input_11;
        this.sue_trim_value_input_12 = sue_trim_value_input_12;
        this.sue_number_of_inputs = sue_number_of_inputs;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_serial_udb_extra_f20( short sue_trim_value_input_1, short sue_trim_value_input_2, short sue_trim_value_input_3, short sue_trim_value_input_4, short sue_trim_value_input_5, short sue_trim_value_input_6, short sue_trim_value_input_7, short sue_trim_value_input_8, short sue_trim_value_input_9, short sue_trim_value_input_10, short sue_trim_value_input_11, short sue_trim_value_input_12, short sue_number_of_inputs, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F20;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sue_trim_value_input_1 = sue_trim_value_input_1;
        this.sue_trim_value_input_2 = sue_trim_value_input_2;
        this.sue_trim_value_input_3 = sue_trim_value_input_3;
        this.sue_trim_value_input_4 = sue_trim_value_input_4;
        this.sue_trim_value_input_5 = sue_trim_value_input_5;
        this.sue_trim_value_input_6 = sue_trim_value_input_6;
        this.sue_trim_value_input_7 = sue_trim_value_input_7;
        this.sue_trim_value_input_8 = sue_trim_value_input_8;
        this.sue_trim_value_input_9 = sue_trim_value_input_9;
        this.sue_trim_value_input_10 = sue_trim_value_input_10;
        this.sue_trim_value_input_11 = sue_trim_value_input_11;
        this.sue_trim_value_input_12 = sue_trim_value_input_12;
        this.sue_number_of_inputs = sue_number_of_inputs;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_serial_udb_extra_f20(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F20;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                              
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F20 - sysid:"+sysid+" compid:"+compid+" sue_trim_value_input_1:"+sue_trim_value_input_1+" sue_trim_value_input_2:"+sue_trim_value_input_2+" sue_trim_value_input_3:"+sue_trim_value_input_3+" sue_trim_value_input_4:"+sue_trim_value_input_4+" sue_trim_value_input_5:"+sue_trim_value_input_5+" sue_trim_value_input_6:"+sue_trim_value_input_6+" sue_trim_value_input_7:"+sue_trim_value_input_7+" sue_trim_value_input_8:"+sue_trim_value_input_8+" sue_trim_value_input_9:"+sue_trim_value_input_9+" sue_trim_value_input_10:"+sue_trim_value_input_10+" sue_trim_value_input_11:"+sue_trim_value_input_11+" sue_trim_value_input_12:"+sue_trim_value_input_12+" sue_number_of_inputs:"+sue_number_of_inputs+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F20";
    }
}
        