/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SERIAL_UDB_EXTRA_F19 PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F19 format
 */
public class msg_serial_udb_extra_f19 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F19 = 185;
    public static final int MAVLINK_MSG_LENGTH = 8;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F19;

    
    /**
     * SUE aileron output channel
     */
    @Description("SUE aileron output channel")
    @Units("")
    public short sue_aileron_output_channel;
    
    /**
     * SUE aileron reversed
     */
    @Description("SUE aileron reversed")
    @Units("")
    public short sue_aileron_reversed;
    
    /**
     * SUE elevator output channel
     */
    @Description("SUE elevator output channel")
    @Units("")
    public short sue_elevator_output_channel;
    
    /**
     * SUE elevator reversed
     */
    @Description("SUE elevator reversed")
    @Units("")
    public short sue_elevator_reversed;
    
    /**
     * SUE throttle output channel
     */
    @Description("SUE throttle output channel")
    @Units("")
    public short sue_throttle_output_channel;
    
    /**
     * SUE throttle reversed
     */
    @Description("SUE throttle reversed")
    @Units("")
    public short sue_throttle_reversed;
    
    /**
     * SUE rudder output channel
     */
    @Description("SUE rudder output channel")
    @Units("")
    public short sue_rudder_output_channel;
    
    /**
     * SUE rudder reversed
     */
    @Description("SUE rudder reversed")
    @Units("")
    public short sue_rudder_reversed;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F19;

        packet.payload.putUnsignedByte(sue_aileron_output_channel);
        packet.payload.putUnsignedByte(sue_aileron_reversed);
        packet.payload.putUnsignedByte(sue_elevator_output_channel);
        packet.payload.putUnsignedByte(sue_elevator_reversed);
        packet.payload.putUnsignedByte(sue_throttle_output_channel);
        packet.payload.putUnsignedByte(sue_throttle_reversed);
        packet.payload.putUnsignedByte(sue_rudder_output_channel);
        packet.payload.putUnsignedByte(sue_rudder_reversed);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a serial_udb_extra_f19 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.sue_aileron_output_channel = payload.getUnsignedByte();
        this.sue_aileron_reversed = payload.getUnsignedByte();
        this.sue_elevator_output_channel = payload.getUnsignedByte();
        this.sue_elevator_reversed = payload.getUnsignedByte();
        this.sue_throttle_output_channel = payload.getUnsignedByte();
        this.sue_throttle_reversed = payload.getUnsignedByte();
        this.sue_rudder_output_channel = payload.getUnsignedByte();
        this.sue_rudder_reversed = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_serial_udb_extra_f19() {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F19;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_serial_udb_extra_f19( short sue_aileron_output_channel, short sue_aileron_reversed, short sue_elevator_output_channel, short sue_elevator_reversed, short sue_throttle_output_channel, short sue_throttle_reversed, short sue_rudder_output_channel, short sue_rudder_reversed) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F19;

        this.sue_aileron_output_channel = sue_aileron_output_channel;
        this.sue_aileron_reversed = sue_aileron_reversed;
        this.sue_elevator_output_channel = sue_elevator_output_channel;
        this.sue_elevator_reversed = sue_elevator_reversed;
        this.sue_throttle_output_channel = sue_throttle_output_channel;
        this.sue_throttle_reversed = sue_throttle_reversed;
        this.sue_rudder_output_channel = sue_rudder_output_channel;
        this.sue_rudder_reversed = sue_rudder_reversed;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_serial_udb_extra_f19( short sue_aileron_output_channel, short sue_aileron_reversed, short sue_elevator_output_channel, short sue_elevator_reversed, short sue_throttle_output_channel, short sue_throttle_reversed, short sue_rudder_output_channel, short sue_rudder_reversed, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F19;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sue_aileron_output_channel = sue_aileron_output_channel;
        this.sue_aileron_reversed = sue_aileron_reversed;
        this.sue_elevator_output_channel = sue_elevator_output_channel;
        this.sue_elevator_reversed = sue_elevator_reversed;
        this.sue_throttle_output_channel = sue_throttle_output_channel;
        this.sue_throttle_reversed = sue_throttle_reversed;
        this.sue_rudder_output_channel = sue_rudder_output_channel;
        this.sue_rudder_reversed = sue_rudder_reversed;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_serial_udb_extra_f19(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F19;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                    
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F19 - sysid:"+sysid+" compid:"+compid+" sue_aileron_output_channel:"+sue_aileron_output_channel+" sue_aileron_reversed:"+sue_aileron_reversed+" sue_elevator_output_channel:"+sue_elevator_output_channel+" sue_elevator_reversed:"+sue_elevator_reversed+" sue_throttle_output_channel:"+sue_throttle_output_channel+" sue_throttle_reversed:"+sue_throttle_reversed+" sue_rudder_output_channel:"+sue_rudder_output_channel+" sue_rudder_reversed:"+sue_rudder_reversed+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F19";
    }
}
        