/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE FLEXIFUNCTION_DIRECTORY PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Acknowldge success or failure of a flexifunction command
 */
public class msg_flexifunction_directory extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_FLEXIFUNCTION_DIRECTORY = 155;
    public static final int MAVLINK_MSG_LENGTH = 53;
    private static final long serialVersionUID = MAVLINK_MSG_ID_FLEXIFUNCTION_DIRECTORY;

    
    /**
     * System ID
     */
    @Description("System ID")
    @Units("")
    public short target_system;
    
    /**
     * Component ID
     */
    @Description("Component ID")
    @Units("")
    public short target_component;
    
    /**
     * 0=inputs, 1=outputs
     */
    @Description("0=inputs, 1=outputs")
    @Units("")
    public short directory_type;
    
    /**
     * index of first directory entry to write
     */
    @Description("index of first directory entry to write")
    @Units("")
    public short start_index;
    
    /**
     * count of directory entries to write
     */
    @Description("count of directory entries to write")
    @Units("")
    public short count;
    
    /**
     * Settings data
     */
    @Description("Settings data")
    @Units("")
    public byte directory_data[] = new byte[48];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_DIRECTORY;

        packet.payload.putUnsignedByte(target_system);
        packet.payload.putUnsignedByte(target_component);
        packet.payload.putUnsignedByte(directory_type);
        packet.payload.putUnsignedByte(start_index);
        packet.payload.putUnsignedByte(count);
        
        for (int i = 0; i < directory_data.length; i++) {
            packet.payload.putByte(directory_data[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a flexifunction_directory message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.target_system = payload.getUnsignedByte();
        this.target_component = payload.getUnsignedByte();
        this.directory_type = payload.getUnsignedByte();
        this.start_index = payload.getUnsignedByte();
        this.count = payload.getUnsignedByte();
        
        for (int i = 0; i < this.directory_data.length; i++) {
            this.directory_data[i] = payload.getByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_flexifunction_directory() {
        this.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_DIRECTORY;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_flexifunction_directory( short target_system, short target_component, short directory_type, short start_index, short count, byte[] directory_data) {
        this.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_DIRECTORY;

        this.target_system = target_system;
        this.target_component = target_component;
        this.directory_type = directory_type;
        this.start_index = start_index;
        this.count = count;
        this.directory_data = directory_data;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_flexifunction_directory( short target_system, short target_component, short directory_type, short start_index, short count, byte[] directory_data, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_DIRECTORY;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.target_system = target_system;
        this.target_component = target_component;
        this.directory_type = directory_type;
        this.start_index = start_index;
        this.count = count;
        this.directory_data = directory_data;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_flexifunction_directory(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_DIRECTORY;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_FLEXIFUNCTION_DIRECTORY - sysid:"+sysid+" compid:"+compid+" target_system:"+target_system+" target_component:"+target_component+" directory_type:"+directory_type+" start_index:"+start_index+" count:"+count+" directory_data:"+directory_data+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_FLEXIFUNCTION_DIRECTORY";
    }
}
        