/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE FLEXIFUNCTION_COMMAND_ACK PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Acknowldge success or failure of a flexifunction command
 */
public class msg_flexifunction_command_ack extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_FLEXIFUNCTION_COMMAND_ACK = 158;
    public static final int MAVLINK_MSG_LENGTH = 4;
    private static final long serialVersionUID = MAVLINK_MSG_ID_FLEXIFUNCTION_COMMAND_ACK;

    
    /**
     * Command acknowledged
     */
    @Description("Command acknowledged")
    @Units("")
    public int command_type;
    
    /**
     * result of acknowledge
     */
    @Description("result of acknowledge")
    @Units("")
    public int result;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_COMMAND_ACK;

        packet.payload.putUnsignedShort(command_type);
        packet.payload.putUnsignedShort(result);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a flexifunction_command_ack message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.command_type = payload.getUnsignedShort();
        this.result = payload.getUnsignedShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_flexifunction_command_ack() {
        this.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_COMMAND_ACK;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_flexifunction_command_ack( int command_type, int result) {
        this.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_COMMAND_ACK;

        this.command_type = command_type;
        this.result = result;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_flexifunction_command_ack( int command_type, int result, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_COMMAND_ACK;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.command_type = command_type;
        this.result = result;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_flexifunction_command_ack(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_FLEXIFUNCTION_COMMAND_ACK;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_FLEXIFUNCTION_COMMAND_ACK - sysid:"+sysid+" compid:"+compid+" command_type:"+command_type+" result:"+result+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_FLEXIFUNCTION_COMMAND_ACK";
    }
}
        