/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SERIAL_UDB_EXTRA_F7 PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F7: format
 */
public class msg_serial_udb_extra_f7 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F7 = 175;
    public static final int MAVLINK_MSG_LENGTH = 24;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F7;

    
    /**
     * Serial UDB YAWKP_RUDDER Gain for Proporional control of navigation
     */
    @Description("Serial UDB YAWKP_RUDDER Gain for Proporional control of navigation")
    @Units("")
    public float sue_YAWKP_RUDDER;
    
    /**
     * Serial UDB YAWKD_RUDDER Gain for Rate control of navigation
     */
    @Description("Serial UDB YAWKD_RUDDER Gain for Rate control of navigation")
    @Units("")
    public float sue_YAWKD_RUDDER;
    
    /**
     * Serial UDB Extra ROLLKP_RUDDER Gain for Proportional control of roll stabilization
     */
    @Description("Serial UDB Extra ROLLKP_RUDDER Gain for Proportional control of roll stabilization")
    @Units("")
    public float sue_ROLLKP_RUDDER;
    
    /**
     * Serial UDB Extra ROLLKD_RUDDER Gain for Rate control of roll stabilization
     */
    @Description("Serial UDB Extra ROLLKD_RUDDER Gain for Rate control of roll stabilization")
    @Units("")
    public float sue_ROLLKD_RUDDER;
    
    /**
     * SERIAL UDB EXTRA Rudder Boost Gain to Manual Control when stabilized
     */
    @Description("SERIAL UDB EXTRA Rudder Boost Gain to Manual Control when stabilized")
    @Units("")
    public float sue_RUDDER_BOOST;
    
    /**
     * Serial UDB Extra Return To Landing - Angle to Pitch Plane Down
     */
    @Description("Serial UDB Extra Return To Landing - Angle to Pitch Plane Down")
    @Units("")
    public float sue_RTL_PITCH_DOWN;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F7;

        packet.payload.putFloat(sue_YAWKP_RUDDER);
        packet.payload.putFloat(sue_YAWKD_RUDDER);
        packet.payload.putFloat(sue_ROLLKP_RUDDER);
        packet.payload.putFloat(sue_ROLLKD_RUDDER);
        packet.payload.putFloat(sue_RUDDER_BOOST);
        packet.payload.putFloat(sue_RTL_PITCH_DOWN);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a serial_udb_extra_f7 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.sue_YAWKP_RUDDER = payload.getFloat();
        this.sue_YAWKD_RUDDER = payload.getFloat();
        this.sue_ROLLKP_RUDDER = payload.getFloat();
        this.sue_ROLLKD_RUDDER = payload.getFloat();
        this.sue_RUDDER_BOOST = payload.getFloat();
        this.sue_RTL_PITCH_DOWN = payload.getFloat();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_serial_udb_extra_f7() {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F7;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_serial_udb_extra_f7( float sue_YAWKP_RUDDER, float sue_YAWKD_RUDDER, float sue_ROLLKP_RUDDER, float sue_ROLLKD_RUDDER, float sue_RUDDER_BOOST, float sue_RTL_PITCH_DOWN) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F7;

        this.sue_YAWKP_RUDDER = sue_YAWKP_RUDDER;
        this.sue_YAWKD_RUDDER = sue_YAWKD_RUDDER;
        this.sue_ROLLKP_RUDDER = sue_ROLLKP_RUDDER;
        this.sue_ROLLKD_RUDDER = sue_ROLLKD_RUDDER;
        this.sue_RUDDER_BOOST = sue_RUDDER_BOOST;
        this.sue_RTL_PITCH_DOWN = sue_RTL_PITCH_DOWN;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_serial_udb_extra_f7( float sue_YAWKP_RUDDER, float sue_YAWKD_RUDDER, float sue_ROLLKP_RUDDER, float sue_ROLLKD_RUDDER, float sue_RUDDER_BOOST, float sue_RTL_PITCH_DOWN, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F7;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sue_YAWKP_RUDDER = sue_YAWKP_RUDDER;
        this.sue_YAWKD_RUDDER = sue_YAWKD_RUDDER;
        this.sue_ROLLKP_RUDDER = sue_ROLLKP_RUDDER;
        this.sue_ROLLKD_RUDDER = sue_ROLLKD_RUDDER;
        this.sue_RUDDER_BOOST = sue_RUDDER_BOOST;
        this.sue_RTL_PITCH_DOWN = sue_RTL_PITCH_DOWN;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_serial_udb_extra_f7(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F7;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F7 - sysid:"+sysid+" compid:"+compid+" sue_YAWKP_RUDDER:"+sue_YAWKP_RUDDER+" sue_YAWKD_RUDDER:"+sue_YAWKD_RUDDER+" sue_ROLLKP_RUDDER:"+sue_ROLLKP_RUDDER+" sue_ROLLKD_RUDDER:"+sue_ROLLKD_RUDDER+" sue_RUDDER_BOOST:"+sue_RUDDER_BOOST+" sue_RTL_PITCH_DOWN:"+sue_RTL_PITCH_DOWN+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F7";
    }
}
        