/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SERIAL_UDB_EXTRA_F21 PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F21 format
 */
public class msg_serial_udb_extra_f21 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F21 = 187;
    public static final int MAVLINK_MSG_LENGTH = 12;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F21;

    
    /**
     * SUE X accelerometer offset
     */
    @Description("SUE X accelerometer offset")
    @Units("")
    public short sue_accel_x_offset;
    
    /**
     * SUE Y accelerometer offset
     */
    @Description("SUE Y accelerometer offset")
    @Units("")
    public short sue_accel_y_offset;
    
    /**
     * SUE Z accelerometer offset
     */
    @Description("SUE Z accelerometer offset")
    @Units("")
    public short sue_accel_z_offset;
    
    /**
     * SUE X gyro offset
     */
    @Description("SUE X gyro offset")
    @Units("")
    public short sue_gyro_x_offset;
    
    /**
     * SUE Y gyro offset
     */
    @Description("SUE Y gyro offset")
    @Units("")
    public short sue_gyro_y_offset;
    
    /**
     * SUE Z gyro offset
     */
    @Description("SUE Z gyro offset")
    @Units("")
    public short sue_gyro_z_offset;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F21;

        packet.payload.putShort(sue_accel_x_offset);
        packet.payload.putShort(sue_accel_y_offset);
        packet.payload.putShort(sue_accel_z_offset);
        packet.payload.putShort(sue_gyro_x_offset);
        packet.payload.putShort(sue_gyro_y_offset);
        packet.payload.putShort(sue_gyro_z_offset);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a serial_udb_extra_f21 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.sue_accel_x_offset = payload.getShort();
        this.sue_accel_y_offset = payload.getShort();
        this.sue_accel_z_offset = payload.getShort();
        this.sue_gyro_x_offset = payload.getShort();
        this.sue_gyro_y_offset = payload.getShort();
        this.sue_gyro_z_offset = payload.getShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_serial_udb_extra_f21() {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F21;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_serial_udb_extra_f21( short sue_accel_x_offset, short sue_accel_y_offset, short sue_accel_z_offset, short sue_gyro_x_offset, short sue_gyro_y_offset, short sue_gyro_z_offset) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F21;

        this.sue_accel_x_offset = sue_accel_x_offset;
        this.sue_accel_y_offset = sue_accel_y_offset;
        this.sue_accel_z_offset = sue_accel_z_offset;
        this.sue_gyro_x_offset = sue_gyro_x_offset;
        this.sue_gyro_y_offset = sue_gyro_y_offset;
        this.sue_gyro_z_offset = sue_gyro_z_offset;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_serial_udb_extra_f21( short sue_accel_x_offset, short sue_accel_y_offset, short sue_accel_z_offset, short sue_gyro_x_offset, short sue_gyro_y_offset, short sue_gyro_z_offset, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F21;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sue_accel_x_offset = sue_accel_x_offset;
        this.sue_accel_y_offset = sue_accel_y_offset;
        this.sue_accel_z_offset = sue_accel_z_offset;
        this.sue_gyro_x_offset = sue_gyro_x_offset;
        this.sue_gyro_y_offset = sue_gyro_y_offset;
        this.sue_gyro_z_offset = sue_gyro_z_offset;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_serial_udb_extra_f21(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F21;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F21 - sysid:"+sysid+" compid:"+compid+" sue_accel_x_offset:"+sue_accel_x_offset+" sue_accel_y_offset:"+sue_accel_y_offset+" sue_accel_z_offset:"+sue_accel_z_offset+" sue_gyro_x_offset:"+sue_gyro_x_offset+" sue_gyro_y_offset:"+sue_gyro_y_offset+" sue_gyro_z_offset:"+sue_gyro_z_offset+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F21";
    }
}
        