/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SERIAL_UDB_EXTRA_F15 PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F15 format
 */
public class msg_serial_udb_extra_f15 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F15 = 179;
    public static final int MAVLINK_MSG_LENGTH = 60;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F15;

    
    /**
     * Serial UDB Extra Model Name Of Vehicle
     */
    @Description("Serial UDB Extra Model Name Of Vehicle")
    @Units("")
    public short sue_ID_VEHICLE_MODEL_NAME[] = new short[40];
    
    /**
     * Serial UDB Extra Registraton Number of Vehicle
     */
    @Description("Serial UDB Extra Registraton Number of Vehicle")
    @Units("")
    public short sue_ID_VEHICLE_REGISTRATION[] = new short[20];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F15;

        
        for (int i = 0; i < sue_ID_VEHICLE_MODEL_NAME.length; i++) {
            packet.payload.putUnsignedByte(sue_ID_VEHICLE_MODEL_NAME[i]);
        }
                    
        
        for (int i = 0; i < sue_ID_VEHICLE_REGISTRATION.length; i++) {
            packet.payload.putUnsignedByte(sue_ID_VEHICLE_REGISTRATION[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a serial_udb_extra_f15 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        
        for (int i = 0; i < this.sue_ID_VEHICLE_MODEL_NAME.length; i++) {
            this.sue_ID_VEHICLE_MODEL_NAME[i] = payload.getUnsignedByte();
        }
                
        
        for (int i = 0; i < this.sue_ID_VEHICLE_REGISTRATION.length; i++) {
            this.sue_ID_VEHICLE_REGISTRATION[i] = payload.getUnsignedByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_serial_udb_extra_f15() {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F15;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_serial_udb_extra_f15( short[] sue_ID_VEHICLE_MODEL_NAME, short[] sue_ID_VEHICLE_REGISTRATION) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F15;

        this.sue_ID_VEHICLE_MODEL_NAME = sue_ID_VEHICLE_MODEL_NAME;
        this.sue_ID_VEHICLE_REGISTRATION = sue_ID_VEHICLE_REGISTRATION;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_serial_udb_extra_f15( short[] sue_ID_VEHICLE_MODEL_NAME, short[] sue_ID_VEHICLE_REGISTRATION, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F15;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sue_ID_VEHICLE_MODEL_NAME = sue_ID_VEHICLE_MODEL_NAME;
        this.sue_ID_VEHICLE_REGISTRATION = sue_ID_VEHICLE_REGISTRATION;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_serial_udb_extra_f15(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F15;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F15 - sysid:"+sysid+" compid:"+compid+" sue_ID_VEHICLE_MODEL_NAME:"+sue_ID_VEHICLE_MODEL_NAME+" sue_ID_VEHICLE_REGISTRATION:"+sue_ID_VEHICLE_REGISTRATION+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F15";
    }
}
        