/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SERIAL_UDB_EXTRA_F16 PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F16 format
 */
public class msg_serial_udb_extra_f16 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F16 = 180;
    public static final int MAVLINK_MSG_LENGTH = 110;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F16;

    
    /**
     * Serial UDB Extra Name of Expected Lead Pilot
     */
    @Description("Serial UDB Extra Name of Expected Lead Pilot")
    @Units("")
    public short sue_ID_LEAD_PILOT[] = new short[40];
    
    /**
     * Serial UDB Extra URL of Lead Pilot or Team
     */
    @Description("Serial UDB Extra URL of Lead Pilot or Team")
    @Units("")
    public short sue_ID_DIY_DRONES_URL[] = new short[70];
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F16;

        
        for (int i = 0; i < sue_ID_LEAD_PILOT.length; i++) {
            packet.payload.putUnsignedByte(sue_ID_LEAD_PILOT[i]);
        }
                    
        
        for (int i = 0; i < sue_ID_DIY_DRONES_URL.length; i++) {
            packet.payload.putUnsignedByte(sue_ID_DIY_DRONES_URL[i]);
        }
                    
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a serial_udb_extra_f16 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        
        for (int i = 0; i < this.sue_ID_LEAD_PILOT.length; i++) {
            this.sue_ID_LEAD_PILOT[i] = payload.getUnsignedByte();
        }
                
        
        for (int i = 0; i < this.sue_ID_DIY_DRONES_URL.length; i++) {
            this.sue_ID_DIY_DRONES_URL[i] = payload.getUnsignedByte();
        }
                
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_serial_udb_extra_f16() {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F16;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_serial_udb_extra_f16( short[] sue_ID_LEAD_PILOT, short[] sue_ID_DIY_DRONES_URL) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F16;

        this.sue_ID_LEAD_PILOT = sue_ID_LEAD_PILOT;
        this.sue_ID_DIY_DRONES_URL = sue_ID_DIY_DRONES_URL;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_serial_udb_extra_f16( short[] sue_ID_LEAD_PILOT, short[] sue_ID_DIY_DRONES_URL, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F16;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sue_ID_LEAD_PILOT = sue_ID_LEAD_PILOT;
        this.sue_ID_DIY_DRONES_URL = sue_ID_DIY_DRONES_URL;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_serial_udb_extra_f16(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F16;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

        
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F16 - sysid:"+sysid+" compid:"+compid+" sue_ID_LEAD_PILOT:"+sue_ID_LEAD_PILOT+" sue_ID_DIY_DRONES_URL:"+sue_ID_DIY_DRONES_URL+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F16";
    }
}
        