/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SERIAL_UDB_EXTRA_F13 PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F13: format
 */
public class msg_serial_udb_extra_f13 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F13 = 177;
    public static final int MAVLINK_MSG_LENGTH = 14;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F13;

    
    /**
     * Serial UDB Extra MP Origin Latitude
     */
    @Description("Serial UDB Extra MP Origin Latitude")
    @Units("")
    public int sue_lat_origin;
    
    /**
     * Serial UDB Extra MP Origin Longitude
     */
    @Description("Serial UDB Extra MP Origin Longitude")
    @Units("")
    public int sue_lon_origin;
    
    /**
     * Serial UDB Extra MP Origin Altitude Above Sea Level
     */
    @Description("Serial UDB Extra MP Origin Altitude Above Sea Level")
    @Units("")
    public int sue_alt_origin;
    
    /**
     * Serial UDB Extra GPS Week Number
     */
    @Description("Serial UDB Extra GPS Week Number")
    @Units("")
    public short sue_week_no;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F13;

        packet.payload.putInt(sue_lat_origin);
        packet.payload.putInt(sue_lon_origin);
        packet.payload.putInt(sue_alt_origin);
        packet.payload.putShort(sue_week_no);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a serial_udb_extra_f13 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.sue_lat_origin = payload.getInt();
        this.sue_lon_origin = payload.getInt();
        this.sue_alt_origin = payload.getInt();
        this.sue_week_no = payload.getShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_serial_udb_extra_f13() {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F13;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_serial_udb_extra_f13( int sue_lat_origin, int sue_lon_origin, int sue_alt_origin, short sue_week_no) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F13;

        this.sue_lat_origin = sue_lat_origin;
        this.sue_lon_origin = sue_lon_origin;
        this.sue_alt_origin = sue_alt_origin;
        this.sue_week_no = sue_week_no;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_serial_udb_extra_f13( int sue_lat_origin, int sue_lon_origin, int sue_alt_origin, short sue_week_no, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F13;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sue_lat_origin = sue_lat_origin;
        this.sue_lon_origin = sue_lon_origin;
        this.sue_alt_origin = sue_alt_origin;
        this.sue_week_no = sue_week_no;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_serial_udb_extra_f13(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F13;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

            
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F13 - sysid:"+sysid+" compid:"+compid+" sue_lat_origin:"+sue_lat_origin+" sue_lon_origin:"+sue_lon_origin+" sue_alt_origin:"+sue_alt_origin+" sue_week_no:"+sue_week_no+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F13";
    }
}
        