/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SERIAL_UDB_EXTRA_F22 PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * Backwards compatible version of SERIAL_UDB_EXTRA F22 format
 */
public class msg_serial_udb_extra_f22 extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F22 = 188;
    public static final int MAVLINK_MSG_LENGTH = 12;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F22;

    
    /**
     * SUE X accelerometer at calibration time
     */
    @Description("SUE X accelerometer at calibration time")
    @Units("")
    public short sue_accel_x_at_calibration;
    
    /**
     * SUE Y accelerometer at calibration time
     */
    @Description("SUE Y accelerometer at calibration time")
    @Units("")
    public short sue_accel_y_at_calibration;
    
    /**
     * SUE Z accelerometer at calibration time
     */
    @Description("SUE Z accelerometer at calibration time")
    @Units("")
    public short sue_accel_z_at_calibration;
    
    /**
     * SUE X gyro at calibration time
     */
    @Description("SUE X gyro at calibration time")
    @Units("")
    public short sue_gyro_x_at_calibration;
    
    /**
     * SUE Y gyro at calibration time
     */
    @Description("SUE Y gyro at calibration time")
    @Units("")
    public short sue_gyro_y_at_calibration;
    
    /**
     * SUE Z gyro at calibration time
     */
    @Description("SUE Z gyro at calibration time")
    @Units("")
    public short sue_gyro_z_at_calibration;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F22;

        packet.payload.putShort(sue_accel_x_at_calibration);
        packet.payload.putShort(sue_accel_y_at_calibration);
        packet.payload.putShort(sue_accel_z_at_calibration);
        packet.payload.putShort(sue_gyro_x_at_calibration);
        packet.payload.putShort(sue_gyro_y_at_calibration);
        packet.payload.putShort(sue_gyro_z_at_calibration);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a serial_udb_extra_f22 message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.sue_accel_x_at_calibration = payload.getShort();
        this.sue_accel_y_at_calibration = payload.getShort();
        this.sue_accel_z_at_calibration = payload.getShort();
        this.sue_gyro_x_at_calibration = payload.getShort();
        this.sue_gyro_y_at_calibration = payload.getShort();
        this.sue_gyro_z_at_calibration = payload.getShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_serial_udb_extra_f22() {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F22;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_serial_udb_extra_f22( short sue_accel_x_at_calibration, short sue_accel_y_at_calibration, short sue_accel_z_at_calibration, short sue_gyro_x_at_calibration, short sue_gyro_y_at_calibration, short sue_gyro_z_at_calibration) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F22;

        this.sue_accel_x_at_calibration = sue_accel_x_at_calibration;
        this.sue_accel_y_at_calibration = sue_accel_y_at_calibration;
        this.sue_accel_z_at_calibration = sue_accel_z_at_calibration;
        this.sue_gyro_x_at_calibration = sue_gyro_x_at_calibration;
        this.sue_gyro_y_at_calibration = sue_gyro_y_at_calibration;
        this.sue_gyro_z_at_calibration = sue_gyro_z_at_calibration;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_serial_udb_extra_f22( short sue_accel_x_at_calibration, short sue_accel_y_at_calibration, short sue_accel_z_at_calibration, short sue_gyro_x_at_calibration, short sue_gyro_y_at_calibration, short sue_gyro_z_at_calibration, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F22;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.sue_accel_x_at_calibration = sue_accel_x_at_calibration;
        this.sue_accel_y_at_calibration = sue_accel_y_at_calibration;
        this.sue_accel_z_at_calibration = sue_accel_z_at_calibration;
        this.sue_gyro_x_at_calibration = sue_gyro_x_at_calibration;
        this.sue_gyro_y_at_calibration = sue_gyro_y_at_calibration;
        this.sue_gyro_z_at_calibration = sue_gyro_z_at_calibration;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_serial_udb_extra_f22(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F22;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F22 - sysid:"+sysid+" compid:"+compid+" sue_accel_x_at_calibration:"+sue_accel_x_at_calibration+" sue_accel_y_at_calibration:"+sue_accel_y_at_calibration+" sue_accel_z_at_calibration:"+sue_accel_z_at_calibration+" sue_gyro_x_at_calibration:"+sue_gyro_x_at_calibration+" sue_gyro_y_at_calibration:"+sue_gyro_y_at_calibration+" sue_gyro_z_at_calibration:"+sue_gyro_z_at_calibration+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SERIAL_UDB_EXTRA_F22";
    }
}
        