/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE ALTITUDES PACKING
package com.MAVLink.matrixpilot;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * The altitude measured by sensors and IMU
 */
public class msg_altitudes extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_ALTITUDES = 181;
    public static final int MAVLINK_MSG_LENGTH = 28;
    private static final long serialVersionUID = MAVLINK_MSG_ID_ALTITUDES;

    
    /**
     * Timestamp (milliseconds since system boot)
     */
    @Description("Timestamp (milliseconds since system boot)")
    @Units("")
    public long time_boot_ms;
    
    /**
     * GPS altitude (MSL) in meters, expressed as * 1000 (millimeters)
     */
    @Description("GPS altitude (MSL) in meters, expressed as * 1000 (millimeters)")
    @Units("")
    public int alt_gps;
    
    /**
     * IMU altitude above ground in meters, expressed as * 1000 (millimeters)
     */
    @Description("IMU altitude above ground in meters, expressed as * 1000 (millimeters)")
    @Units("")
    public int alt_imu;
    
    /**
     * barometeric altitude above ground in meters, expressed as * 1000 (millimeters)
     */
    @Description("barometeric altitude above ground in meters, expressed as * 1000 (millimeters)")
    @Units("")
    public int alt_barometric;
    
    /**
     * Optical flow altitude above ground in meters, expressed as * 1000 (millimeters)
     */
    @Description("Optical flow altitude above ground in meters, expressed as * 1000 (millimeters)")
    @Units("")
    public int alt_optical_flow;
    
    /**
     * Rangefinder Altitude above ground in meters, expressed as * 1000 (millimeters)
     */
    @Description("Rangefinder Altitude above ground in meters, expressed as * 1000 (millimeters)")
    @Units("")
    public int alt_range_finder;
    
    /**
     * Extra altitude above ground in meters, expressed as * 1000 (millimeters)
     */
    @Description("Extra altitude above ground in meters, expressed as * 1000 (millimeters)")
    @Units("")
    public int alt_extra;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_ALTITUDES;

        packet.payload.putUnsignedInt(time_boot_ms);
        packet.payload.putInt(alt_gps);
        packet.payload.putInt(alt_imu);
        packet.payload.putInt(alt_barometric);
        packet.payload.putInt(alt_optical_flow);
        packet.payload.putInt(alt_range_finder);
        packet.payload.putInt(alt_extra);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a altitudes message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.time_boot_ms = payload.getUnsignedInt();
        this.alt_gps = payload.getInt();
        this.alt_imu = payload.getInt();
        this.alt_barometric = payload.getInt();
        this.alt_optical_flow = payload.getInt();
        this.alt_range_finder = payload.getInt();
        this.alt_extra = payload.getInt();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_altitudes() {
        this.msgid = MAVLINK_MSG_ID_ALTITUDES;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_altitudes( long time_boot_ms, int alt_gps, int alt_imu, int alt_barometric, int alt_optical_flow, int alt_range_finder, int alt_extra) {
        this.msgid = MAVLINK_MSG_ID_ALTITUDES;

        this.time_boot_ms = time_boot_ms;
        this.alt_gps = alt_gps;
        this.alt_imu = alt_imu;
        this.alt_barometric = alt_barometric;
        this.alt_optical_flow = alt_optical_flow;
        this.alt_range_finder = alt_range_finder;
        this.alt_extra = alt_extra;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_altitudes( long time_boot_ms, int alt_gps, int alt_imu, int alt_barometric, int alt_optical_flow, int alt_range_finder, int alt_extra, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_ALTITUDES;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.time_boot_ms = time_boot_ms;
        this.alt_gps = alt_gps;
        this.alt_imu = alt_imu;
        this.alt_barometric = alt_barometric;
        this.alt_optical_flow = alt_optical_flow;
        this.alt_range_finder = alt_range_finder;
        this.alt_extra = alt_extra;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_altitudes(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_ALTITUDES;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                  
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_ALTITUDES - sysid:"+sysid+" compid:"+compid+" time_boot_ms:"+time_boot_ms+" alt_gps:"+alt_gps+" alt_imu:"+alt_imu+" alt_barometric:"+alt_barometric+" alt_optical_flow:"+alt_optical_flow+" alt_range_finder:"+alt_range_finder+" alt_extra:"+alt_extra+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_ALTITUDES";
    }
}
        