/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE FIGURE_EIGHT_EXECUTION_STATUS PACKING
package com.MAVLink.development;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * 
        Vehicle status report that is sent out while figure eight execution is in progress (see MAV_CMD_DO_FIGURE_EIGHT).
        This may typically send at low rates: of the order of 2Hz.
      
 */
public class msg_figure_eight_execution_status extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_FIGURE_EIGHT_EXECUTION_STATUS = 361;
    public static final int MAVLINK_MSG_LENGTH = 33;
    private static final long serialVersionUID = MAVLINK_MSG_ID_FIGURE_EIGHT_EXECUTION_STATUS;

    
    /**
     * Timestamp (UNIX Epoch time or time since system boot). The receiving end can infer timestamp format (since 1.1.1970 or since system boot) by checking for the magnitude of the number.
     */
    @Description("Timestamp (UNIX Epoch time or time since system boot). The receiving end can infer timestamp format (since 1.1.1970 or since system boot) by checking for the magnitude of the number.")
    @Units("us")
    public long time_usec;
    
    /**
     * Major axis radius of the figure eight. Positive: orbit the north circle clockwise. Negative: orbit the north circle counter-clockwise.
     */
    @Description("Major axis radius of the figure eight. Positive: orbit the north circle clockwise. Negative: orbit the north circle counter-clockwise.")
    @Units("m")
    public float major_radius;
    
    /**
     * Minor axis radius of the figure eight. Defines the radius of two circles that make up the figure.
     */
    @Description("Minor axis radius of the figure eight. Defines the radius of two circles that make up the figure.")
    @Units("m")
    public float minor_radius;
    
    /**
     * Orientation of the figure eight major axis with respect to true north in [-pi,pi).
     */
    @Description("Orientation of the figure eight major axis with respect to true north in [-pi,pi).")
    @Units("rad")
    public float orientation;
    
    /**
     * X coordinate of center point. Coordinate system depends on frame field.
     */
    @Description("X coordinate of center point. Coordinate system depends on frame field.")
    @Units("")
    public int x;
    
    /**
     * Y coordinate of center point. Coordinate system depends on frame field.
     */
    @Description("Y coordinate of center point. Coordinate system depends on frame field.")
    @Units("")
    public int y;
    
    /**
     * Altitude of center point. Coordinate system depends on frame field.
     */
    @Description("Altitude of center point. Coordinate system depends on frame field.")
    @Units("m")
    public float z;
    
    /**
     * The coordinate system of the fields: x, y, z.
     */
    @Description("The coordinate system of the fields: x, y, z.")
    @Units("")
    public short frame;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_FIGURE_EIGHT_EXECUTION_STATUS;

        packet.payload.putUnsignedLong(time_usec);
        packet.payload.putFloat(major_radius);
        packet.payload.putFloat(minor_radius);
        packet.payload.putFloat(orientation);
        packet.payload.putInt(x);
        packet.payload.putInt(y);
        packet.payload.putFloat(z);
        packet.payload.putUnsignedByte(frame);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a figure_eight_execution_status message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.time_usec = payload.getUnsignedLong();
        this.major_radius = payload.getFloat();
        this.minor_radius = payload.getFloat();
        this.orientation = payload.getFloat();
        this.x = payload.getInt();
        this.y = payload.getInt();
        this.z = payload.getFloat();
        this.frame = payload.getUnsignedByte();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_figure_eight_execution_status() {
        this.msgid = MAVLINK_MSG_ID_FIGURE_EIGHT_EXECUTION_STATUS;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_figure_eight_execution_status( long time_usec, float major_radius, float minor_radius, float orientation, int x, int y, float z, short frame) {
        this.msgid = MAVLINK_MSG_ID_FIGURE_EIGHT_EXECUTION_STATUS;

        this.time_usec = time_usec;
        this.major_radius = major_radius;
        this.minor_radius = minor_radius;
        this.orientation = orientation;
        this.x = x;
        this.y = y;
        this.z = z;
        this.frame = frame;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_figure_eight_execution_status( long time_usec, float major_radius, float minor_radius, float orientation, int x, int y, float z, short frame, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_FIGURE_EIGHT_EXECUTION_STATUS;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.time_usec = time_usec;
        this.major_radius = major_radius;
        this.minor_radius = minor_radius;
        this.orientation = orientation;
        this.x = x;
        this.y = y;
        this.z = z;
        this.frame = frame;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_figure_eight_execution_status(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_FIGURE_EIGHT_EXECUTION_STATUS;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

                    
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_FIGURE_EIGHT_EXECUTION_STATUS - sysid:"+sysid+" compid:"+compid+" time_usec:"+time_usec+" major_radius:"+major_radius+" minor_radius:"+minor_radius+" orientation:"+orientation+" x:"+x+" y:"+y+" z:"+z+" frame:"+frame+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_FIGURE_EIGHT_EXECUTION_STATUS";
    }
}
        