/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE SCRIPT_CURRENT PACKING
package com.MAVLink.paparazzi;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.Description;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;
import com.MAVLink.Messages.Units;

/**
 * This message informs about the currently active SCRIPT.
 */
public class msg_script_current extends MAVLinkMessage {

    public static final int MAVLINK_MSG_ID_SCRIPT_CURRENT = 184;
    public static final int MAVLINK_MSG_LENGTH = 2;
    private static final long serialVersionUID = MAVLINK_MSG_ID_SCRIPT_CURRENT;

    
    /**
     * Active Sequence
     */
    @Description("Active Sequence")
    @Units("")
    public int seq;
    

    /**
     * Generates the payload for a mavlink message for a message of this type
     * @return
     */
    @Override
    public MAVLinkPacket pack() {
        MAVLinkPacket packet = new MAVLinkPacket(MAVLINK_MSG_LENGTH,isMavlink2);
        packet.sysid = sysid;
        packet.compid = compid;
        packet.msgid = MAVLINK_MSG_ID_SCRIPT_CURRENT;

        packet.payload.putUnsignedShort(seq);
        
        if (isMavlink2) {
            
        }
        return packet;
    }

    /**
     * Decode a script_current message into this class fields
     *
     * @param payload The message to decode
     */
    @Override
    public void unpack(MAVLinkPayload payload) {
        payload.resetIndex();

        this.seq = payload.getUnsignedShort();
        
        if (isMavlink2) {
            
        }
    }

    /**
     * Constructor for a new message, just initializes the msgid
     */
    public msg_script_current() {
        this.msgid = MAVLINK_MSG_ID_SCRIPT_CURRENT;
    }

    /**
     * Constructor for a new message, initializes msgid and all payload variables
     */
    public msg_script_current( int seq) {
        this.msgid = MAVLINK_MSG_ID_SCRIPT_CURRENT;

        this.seq = seq;
        
    }

    /**
     * Constructor for a new message, initializes everything
     */
    public msg_script_current( int seq, int sysid, int compid, boolean isMavlink2) {
        this.msgid = MAVLINK_MSG_ID_SCRIPT_CURRENT;
        this.sysid = sysid;
        this.compid = compid;
        this.isMavlink2 = isMavlink2;

        this.seq = seq;
        
    }

    /**
     * Constructor for a new message, initializes the message with the payload
     * from a mavlink packet
     *
     */
    public msg_script_current(MAVLinkPacket mavLinkPacket) {
        this.msgid = MAVLINK_MSG_ID_SCRIPT_CURRENT;

        this.sysid = mavLinkPacket.sysid;
        this.compid = mavLinkPacket.compid;
        this.isMavlink2 = mavLinkPacket.isMavlink2;
        unpack(mavLinkPacket.payload);
    }

      
    /**
     * Returns a string with the MSG name and data
     */
    @Override
    public String toString() {
        return "MAVLINK_MSG_ID_SCRIPT_CURRENT - sysid:"+sysid+" compid:"+compid+" seq:"+seq+"";
    }

    /**
     * Returns a human-readable string of the name of the message
     */
    @Override
    public String name() {
        return "MAVLINK_MSG_ID_SCRIPT_CURRENT";
    }
}
        