package org.sensorhub.impl.sensor.nmeaais.outputs;

import dk.dma.ais.message.AisMessage18;
import net.opengis.swe.v20.DataBlock;
import net.opengis.swe.v20.DataComponent;
import net.opengis.swe.v20.DataEncoding;
import net.opengis.swe.v20.DataRecord;
import org.sensorhub.api.data.DataEvent;
import org.sensorhub.impl.sensor.VarRateSensorOutput;
import org.sensorhub.impl.sensor.nmeaais.NmeaAisDriver;
import org.vast.swe.SWEBuilders;
import org.vast.swe.SWEHelper;
import org.vast.swe.helper.GeoPosHelper;

public class NmeaAisOutputPositionClassB extends VarRateSensorOutput<NmeaAisDriver> implements NmeaAisReportInterface<AisMessage18> {
    private DataRecord aisReportRecord;
    private DataEncoding dataEncoding;

    private final Object processingLock = new Object();

    public NmeaAisOutputPositionClassB(NmeaAisDriver nmeaAisDriver) {
        super("nmeaAisOutputPositionClassB", nmeaAisDriver,1.0);
    }

    /**
     * Initializes the data structure for the output.
     *
     * Flat index map:
     *   0  = messageId        1  = repeat           2  = mmsi
     *   3  = sog              4  = positionAccuracy
     *   5  = latitude  (lat component of location vector)
     *   6  = longitude (lon component of location vector)
     *   7  = cog              8  = heading          9  = timeStamp
     *   10 = unitFlag         11 = displayFlag      12 = dscFlag
     *   13 = bandFlag         14 = message22Flag    15 = modeFlag
     *   16 = raimFlag         17 = commStateFlag    18 = commState
     *   19 = bits
     */
    public void doInit() {
        GeoPosHelper geoFac = new GeoPosHelper();
        SWEHelper sweFactory = new SWEHelper();

        SWEBuilders.DataRecordBuilder recordBuilder = sweFactory.createRecord()
                .name("nmeaAisOutputPositionClassB")
                .label("Position Report Class B")
                .description("Class B AIS Position Report")
                .definition(SWEHelper.getPropertyUri("NmeaAisOutputPositionClassB"))
                .addField("messageId", sweFactory.createQuantity()
                        .label("Message Id")
                        .description("Identifier for this message 1, 2 or 3")
                        .definition(SWEHelper.getPropertyUri("MessageId")))
                .addField("reportDescription", sweFactory.createText()
                        .label("Report Description")
                        .description("Describes the report based on the Message Id provided")
                        .definition(SWEHelper.getPropertyUri("ReportDescription")))
                .addField("repeat", sweFactory.createQuantity()
                        .label("Repeat Indicator")
                        .description("Used by the repeater to indicate how many times a message has been repeated. See Section 4.6.1, Annex 2; 0-3; 0 = default; 3 = do not repeat any more.")
                        .definition(SWEHelper.getPropertyUri("repeat")))
                .addField("mmsi", sweFactory.createQuantity()
                        .label("MMSI Number")
                        .description("MMSI Number")
                        .definition(SWEHelper.getPropertyUri("Mmsi")))
                .addField("sog", sweFactory.createQuantity()
                        .label("Speed Over Ground")
                        .description("Speed over ground in knots (0–102.2 knots, 102.3 = not available, 102.3+ should not be used)")
                        .uom("[kn_i]")
                        .definition(SWEHelper.getPropertyUri("SpeedOverGround")))
                .addField("positionAccuracy", sweFactory.createQuantity()
                        .label("Position Accuracy")
                        .description(
                                "1 = high (<= 10 m)\n" +
                                "0 = low (> 10 m)\n" +
                                "0 = default"
                        )
                        .definition(SWEHelper.getPropertyUri("PositionAccuracy")))
                .addField("location", geoFac.createLocationVectorLatLon()
                        .label("Location"))
                .addField("cog", sweFactory.createQuantity()
                        .label("COG")
                        .description("Course over ground in 1/10 = (0-3599). 3600 (E10h) = not available = default. 3601-4095 should not be used")
                        .definition(SWEHelper.getPropertyUri("Cog")))
                .addField("heading", sweFactory.createQuantity()
                        .label("True Heading")
                        .uom("deg")
                        .description("Degrees (0-359) (511 indicates not available = default)")
                        .definition(SWEHelper.getPropertyUri("heading")))
                .addField("timeStamp", sweFactory.createTime()
                        .label("Time Stamp")
                        .description("UTC second when the report was generated by the electronic position system (EPFS) (0-59, or 60 if time stamp is not available, which should also be the default value, or 61 if positioning system is in manual input mode, or 62 if electronic position fixing system operates in estimated (dead reckoning) mode, or 63 if the positioning system is inoperative)")
                        .definition(SWEHelper.getPropertyUri("TimeStamp")))
                .addField("unitFlag", sweFactory.createQuantity()
                        .label("Class B Unit Flag")
                        .description("0 (Class B unit) or 1 (Class B CS unit)")
                        .definition(SWEHelper.getPropertyUri("UnitFlag")))
                .addField("displayFlag", sweFactory.createQuantity()
                        .label("Class B Display Flag")
                        .description("0 = No display available; not capable of displaying Message 12 and 14\n" +
                                "1 = Equipped with integrated display displaying Message 12 and 14")
                        .definition(SWEHelper.getPropertyUri("DisplayFlag")))
                .addField("dscFlag", sweFactory.createQuantity()
                        .label("Class B DSC Flag")
                        .description("0 = Not equipped with DSC function\n" +
                                "1 = Equipped with DSC function (dedicated or time-shared)")
                        .definition(SWEHelper.getPropertyUri("DscFlag")))
                .addField("bandFlag", sweFactory.createQuantity()
                        .label("Class B Band Flag")
                        .description("0 = Capable of operating over the upper 525 kHz band of the marine band\n" +
                                "1 = Capable of operating over the whole marine band (irrelevant if \"Class B Message 22 flag\" is 0)")
                        .definition(SWEHelper.getPropertyUri("BandFlag")))
                .addField("message22Flag", sweFactory.createQuantity()
                        .label("Class B Message 22 Flag")
                        .description("0 = No frequency management via Message 22 , operating on AIS1, AIS2 only\n" +
                                "1 = Frequency management via Message 22")
                        .definition(SWEHelper.getPropertyUri("Message22Flag")))
                .addField("modeFlag", sweFactory.createQuantity()
                        .label("Mode Flag")
                        .description("0 = Station operating in autonomous and continuous mode = default\n" +
                                "1 = Station operating in assigned mode")
                        .definition(SWEHelper.getPropertyUri("ModeFlag")))
                .addField("raim", sweFactory.createQuantity()
                        .label("RAIM-flag")
                        .description("Receiver autonomous integrity monitoring (RAIM) flag of electronic position fixing device; 0 = RAIM not in use = default; 1 = RAIM in use. See Table")
                        .definition(SWEHelper.getPropertyUri("Raim")))
                .addField("commStateFlag", sweFactory.createQuantity()
                        .label("Communication State Selector Flag")
                        .description("0 = SOTDMA communication state follows\n" +
                                "1 = ITDMA communication state follows (always 1 for Class-B \"CS\")")
                        .definition(SWEHelper.getPropertyUri("CommStateFlag")))
                .addField("commState", sweFactory.createQuantity()
                        .label("Communication State")
                        .description("OTDMA communication state. Because Class B \"CS\" does not use any Communication State information, this field shall be filled with the following value: 1100000000000000110.")
                        .definition(SWEHelper.getPropertyUri("CommState")));

        aisReportRecord = recordBuilder.build();
        dataEncoding = geoFac.newTextEncoding(",", "\n");
    }

    @Override
    public void setData(AisMessage18 report, String description) {
        synchronized (processingLock) {
            DataBlock dataBlock = latestRecord == null ? aisReportRecord.createDataBlock() : latestRecord.renew();

            dataBlock.setIntValue(0,  report.getUserId());
            dataBlock.setStringValue(1,  description);
            dataBlock.setIntValue(2,  report.getRepeat());
            dataBlock.setIntValue(3,  report.getUserId());
            dataBlock.setDoubleValue(4,  report.getSog() / 10.0);
            dataBlock.setIntValue(5,  report.getPosAcc());
            dataBlock.setDoubleValue(6,  report.getPos().getLatitudeDouble());
            dataBlock.setDoubleValue(7,  report.getPos().getLongitudeDouble());
            dataBlock.setDoubleValue(8,  report.getCog() / 10.0);
            dataBlock.setIntValue(9,  report.getTrueHeading());
            dataBlock.setIntValue(10,  report.getUtcSec());
            dataBlock.setIntValue(11, report.getClassBUnitFlag());
            dataBlock.setIntValue(12, report.getClassBDisplayFlag());
            dataBlock.setIntValue(13, report.getClassBDscFlag());
            dataBlock.setIntValue(14, report.getClassBBandFlag());
            dataBlock.setIntValue(15, report.getClassBMsg22Flag());
            dataBlock.setIntValue(16, report.getModeFlag());
            dataBlock.setIntValue(17, report.getRaim());
            dataBlock.setIntValue(18, report.getCommStateSelectorFlag());
            dataBlock.setIntValue(19, report.getCommState());

            String foiUID = parentSensor.addFoi(report.getUserId());

            latestRecord = dataBlock;
            latestRecordTime = System.currentTimeMillis();
            updateSamplingPeriod(latestRecordTime);
            eventHandler.publish(new DataEvent(latestRecordTime, NmeaAisOutputPositionClassB.this, foiUID, dataBlock));
        }
    }

    @Override
    public DataComponent getRecordDescription() {
        return aisReportRecord;
    }

    @Override
    public DataEncoding getRecommendedEncoding() {
        return dataEncoding;
    }
}
