package org.sensorhub.impl.sensor.nmeaais.outputs;

import net.opengis.swe.v20.DataBlock;
import org.sensorhub.api.data.DataEvent;
import org.sensorhub.impl.sensor.nmeaais.NmeaAisDriver;
import org.sensorhub.impl.sensor.nmeaais.reportschemas.PositionReportClassB;
import org.vast.swe.SWEHelper;
import org.vast.swe.helper.GeoPosHelper;

public class NmeaAisOutputPositionClassB extends NmeaAisOutput implements NmeaAisOutputInterface<PositionReportClassB> {
    private static final String OUTPUT_NAME = "nmeaAisOutputPositionClassB";
    private static final String OUTPUT_LABEL = "Position Report Class B";
    private static final String OUTPUT_DESCRIPTION = "Class B AIS Position Report";
    private static final String OUTPUT_DEFINITION = SWEHelper.getPropertyUri("NmeaAisOutputPositionClassB");

    private final Object processingLock = new Object();

    public NmeaAisOutputPositionClassB(NmeaAisDriver nmeaAisDriver) {
        super(OUTPUT_NAME, nmeaAisDriver);
    }

    /**
     * Initializes the data structure for the output, defining the fields, their ordering, and data types.
     */
    public void doInit() {
        GeoPosHelper geoFac = new GeoPosHelper();
        SWEHelper sweFactory = new SWEHelper();

        aisRecord = createRecordBuilder(OUTPUT_NAME, OUTPUT_LABEL, OUTPUT_DESCRIPTION, OUTPUT_DEFINITION)
                .addField("messageId", sweFactory.createQuantity()
                        .label("Message Id")
                        .description("Identifier for this message 1, 2 or 3")
                        .definition(SWEHelper.getPropertyUri("MessageId")))
                .addField("repeat", sweFactory.createQuantity()
                        .label("Repeat Indicator")
                        .description("Used by the repeater to indicate how many times a message has been repeated. See Section 4.6.1, Annex 2; 0-3; 0 = default; 3 = do not repeat any more.")
                        .definition(SWEHelper.getPropertyUri("repeat")))
                .addField("mmsi", sweFactory.createText()
                        .label("MMSI Number")
                        .description("MMSI Number")
                        .definition(SWEHelper.getPropertyUri("Mmsi")))
                .addField("sog", sweFactory.createQuantity()
                        .label("Speed Over Ground")
                        .description("Speed over ground in knots (0–102.2 knots, 102.3 = not available, 102.3+ should not be used)")
                        .uom("[kn_i]")
                        .definition(SWEHelper.getPropertyUri("SpeedOverGround")))
                .addField("positionAccuracy", sweFactory.createQuantity()
                        .label("Position Accuracy")
                        .description(
                                "1 = high (<= 10 m)\n" +
                                "0 = low (> 10 m)\n" +
                                "0 = default"
                        )
                        .definition(SWEHelper.getPropertyUri("PositionAccuracy")))
                .addField("location", geoFac.createLocationVectorLatLon()
                        .label("Location"))
                .addField("cog", sweFactory.createQuantity()
                        .label("COG")
                        .description("Course over ground in 1/10 = (0-3599). 3600 (E10h) = not available = default. 3601-4095 should not be used")
                        .definition(SWEHelper.getPropertyUri("Cog")))
                .addField("heading", sweFactory.createQuantity()
                        .label("True Heading")
                        .uom("deg")
                        .description("Degrees (0-359) (511 indicates not available = default)")
                        .definition(SWEHelper.getPropertyUri("heading")))
                .addField("timeStamp", sweFactory.createTime()
                        .label("Time Stamp")
                        .description("UTC second when the report was generated by the electronic position system (EPFS) (0-59, or 60 if time stamp is not available, which should also be the default value, or 61 if positioning system is in manual input mode, or 62 if electronic position fixing system operates in estimated (dead reckoning) mode, or 63 if the positioning system is inoperative)")
                        .definition(SWEHelper.getPropertyUri("TimeStamp")))
                .addField("unitFlag", sweFactory.createQuantity()
                        .label("Class B Unit Flag")
                        .description("0 (Class B unit) or 1 (Class B CS unit)")
                        .definition(SWEHelper.getPropertyUri("UnitFlag")))
                .addField("displayFlag", sweFactory.createQuantity()
                        .label("Class B Display Flag")
                        .description("0 = No display available; not capable of displaying Message 12 and 14\n" +
                                "1 = Equipped with integrated display displaying Message 12 and 14")
                        .definition(SWEHelper.getPropertyUri("DisplayFlag")))
                .addField("dscFlag", sweFactory.createQuantity()
                        .label("Class B DSC Flag")
                        .description("0 = Not equipped with DSC function\n" +
                                "1 = Equipped with DSC function (dedicated or time-shared)")
                        .definition(SWEHelper.getPropertyUri("DscFlag")))
                .addField("bandFlag", sweFactory.createQuantity()
                        .label("Class B Band Flag")
                        .description("0 = Capable of operating over the upper 525 kHz band of the marine band\n" +
                                "1 = Capable of operating over the whole marine band (irrelevant if \"Class B Message 22 flag\" is 0)")
                        .definition(SWEHelper.getPropertyUri("BandFlag")))
                .addField("message22Flag", sweFactory.createQuantity()
                        .label("Class B Message 22 Flag")
                        .description("0 = No frequency management via Message 22 , operating on AIS1, AIS2 only\n" +
                                "1 = Frequency management via Message 22")
                        .definition(SWEHelper.getPropertyUri("Message22Flag")))
                .addField("modeFlag", sweFactory.createQuantity()
                        .label("Mode Flag")
                        .description("0 = Station operating in autonomous and continuous mode = default\n" +
                                "1 = Station operating in assigned mode")
                        .definition(SWEHelper.getPropertyUri("ModeFlag")))
                .addField("raim", sweFactory.createQuantity()
                        .label("RAIM-flag")
                        .description("Receiver autonomous integrity monitoring (RAIM) flag of electronic position fixing device; 0 = RAIM not in use = default; 1 = RAIM in use. See Table")
                        .definition(SWEHelper.getPropertyUri("Raim")))
                .addField("commStateFlag", sweFactory.createQuantity()
                        .label("Communication State Selector Flag")
                        .description("0 = SOTDMA communication state follows\n" +
                                "1 = ITDMA communication state follows (always 1 for Class-B \"CS\")")
                        .definition(SWEHelper.getPropertyUri("CommStateFlag")))
                .addField("commState", sweFactory.createQuantity()
                        .label("Communication State")
                        .description("OTDMA communication state. Because Class B \"CS\" does not use any Communication State information, this field shall be filled with the following value: 1100000000000000110.")
                        .definition(SWEHelper.getPropertyUri("CommState")))
                .addField("bits", sweFactory.createQuantity()
                        .label("Number of Bits")
                        .description("Number of Bits")
                        .definition(SWEHelper.getPropertyUri("bits")))
                .build();
        aisRecordSize = 9;

        dataEncoding = geoFac.newTextEncoding(",", "\n");
    }

    /**
     * Sets the data for the output and publishes it.
     */
    @Override
    public void setData(String nmeaAisMsg, PositionReportClassB report) {
        synchronized (processingLock) {
            setAisMsgData(nmeaAisMsg);

            DataBlock dataBlock = latestRecord == null ? aisRecord.createDataBlock() : latestRecord.renew();

            // NMEA envelope fields (flat indices 0–8)
            populateNmeaAisDataStructure(dataBlock);

            // Decoded payload fields (flat indices 10–25)
            dataBlock.setIntValue(aisRecordSize+1,  report.messageId);
            dataBlock.setIntValue(aisRecordSize + 2, report.repeat);
            dataBlock.setStringValue(aisRecordSize + 3, report.mmsi);
            dataBlock.setDoubleValue(aisRecordSize + 4, report.sog);
            dataBlock.setIntValue(aisRecordSize + 5, report.posAccuracy);
            dataBlock.setDoubleValue(aisRecordSize + 6, report.latitude);
            dataBlock.setDoubleValue(aisRecordSize + 7, report.longitude);
            dataBlock.setDoubleValue(aisRecordSize + 8, report.cog);
            dataBlock.setIntValue(aisRecordSize + 9, report.heading);
            dataBlock.setIntValue(aisRecordSize + 10, report.timeStamp);
            dataBlock.setIntValue(aisRecordSize + 11, report.unitFlag);
            dataBlock.setIntValue(aisRecordSize + 12, report.displayFlag);
            dataBlock.setIntValue(aisRecordSize + 13, report.dscFlag);
            dataBlock.setIntValue(aisRecordSize + 14, report.bandFlag);
            dataBlock.setIntValue(aisRecordSize + 15, report.message22Flag);
            dataBlock.setIntValue(aisRecordSize + 16, report.modeFlag);
            dataBlock.setIntValue(aisRecordSize + 17, report.raimFlag);
            dataBlock.setIntValue(aisRecordSize + 18, report.commStateFlag);
            dataBlock.setIntValue(aisRecordSize + 19, report.commState);
            dataBlock.setIntValue(aisRecordSize + 20, report.bits);

            // Register the vessel as a FOI keyed by MMSI
            String foiUID = parentSensor.addFoi(report.mmsi);

            latestRecord = dataBlock;
            latestRecordTime = System.currentTimeMillis();
            updateSamplingPeriod(latestRecordTime);
            eventHandler.publish(new DataEvent(latestRecordTime, NmeaAisOutputPositionClassB.this, foiUID, dataBlock));
        }
    }
}
